### ISSUE TITLE
unable to parse the license 

### ISSUE THREAD

**Issue by mserageng** [WHTJEON/narrowvine-reborn#10]
mpd = https://ec2.vod.etisalattelevision.com/dash-wv/vod-enc/E30000001554720912_2019_12_01T19_50_44Z.xml_L3Sg24MKKp80Js4sTLdd2tmCxJ0n_bJh_xsa9_sony_VBMZ0003450000000000_1.100005.0/default.mpd

license = https://sg-sg-sg.cplane.evision.ae:9443/vgemultidrm/v1/widevine/license

**Comment by WHTJEON** [comment]
It needs extra license headers

**Comment by ank003** [comment]
> It needs extra license headers

Bro can anyone please give the link of working widevine tools like key extractor and mpd extractor and From where we will get that licence key bro...?? Anyone please answer this question  I'm a beginner bro and i have some tools but not working on specific websites now..

**Comment by WHTJEON** [comment]
> > It needs extra license headers
> 
> Bro can anyone please give the link of working widevine tools like key extractor and mpd extractor and From where we will get that licence key bro...?? Anyone please answer this question I'm a beginner bro and i have some tools but not working on specific websites now..

Google it. I can't help you with the basics.
